[package]
name = "minos-proxy"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Minos data plane: listeners, protocol handlers, pipeline executor."

[lints]
workspace = true

[dependencies]
minos-core = { path = "../minos-core" }
minos-config = { path = "../minos-config" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true }
arc-swap = { workspace = true }
httparse = { workspace = true }
async-trait = { workspace = true }
socket2 = { workspace = true }
tracing = { workspace = true }
minos-storage = { path = "../minos-storage" }

[dev-dependencies]
tempfile = { workspace = true }
